### PR TITLE
PT-104 Add diabeloop device "dblg1"

### PR DESCRIPTION
**Pull request by ysdw**
rebase from viz upstream, integrate coyotte508 changes, fix merge errors.
WIP: Translation need to be review.

### CODE REVIEW

**Comment by ysdw** [comment]
Can replace PR https://github.com/mdblp/viz/pull/1 : Add DBLG1

**Review by franck-fourel — CHANGES_REQUESTED** [review]
The data that is displayed in the Device header is not consistent:

image

The main one (red) is the upload date while the second one (yellow) is an effective date.

**Comment by ysdw** [comment]
> The data that is displayed in the Device header is not consistent:
> The main one (red) is the upload date while the second one (yellow) is an effective date.

Yes, i didn't see that I used the same date in my tests, didn't check that.
The tooltip always use the deviceTime, but the displayed time in the title is the uploaded date (and only if it not exists it use the deviceTime).

The best solution I think is to modify `mdblp-common-api/src/api/platform-data.ts` (and probably `portal-api` too, to use the same value for `deviceTime` and `time` fields.

**Comment by franck-fourel** [comment]
ok, Let's track that as a bug.
Let me approved this as it is. 
I'm wondering if we should just have one date that would be the `last updated date`

> > The data that is displayed in the Device header is not consistent:
> > The main one (red) is the upload date while the second one (yellow) is an effective date.
> 
> Yes, i didn't see that I used the same date in my tests, didn't check that.
> The tooltip always use the deviceTime, but the displayed time in the title is the uploaded date (and only if it not exists it use the deviceTime).
> 
> The best solution I think is to modify `mdblp-common-api/src/api/platform-data.ts` (and probably `portal-api` too, to use the same value for `deviceTime` and `time` fields.

**Review by franck-fourel — APPROVED** [review]

**Pull request merged**
