### PR TITLE
PT-1172 Parameter history in Settings don't use timezone

### PR DESCRIPTION
**Pull request by yvon-dblg**
Before:
image

After:
image
-> Use America/Chicago for timezone in theses examples.

The date format used, is one already available in the blip translations:
- English: `MMM D, YYYY h:mm a`
- French: `D MMM YYYY, H:mm`

### CODE REVIEW

**Comment by MarineDBL** [comment]
I wouldn't necessary add a comma after the date in French. As there is none in English. 
In your example **English: MMM D, YYYY h:mm a** what does "a" stand for?

**Comment by yvon-dblg** [comment]
> 
> 
> I wouldn't necessary add a comma after the date in French. As there is none in English.

I use the translation currently available in blip, to avoid having to add a new one. If you have some proposal, we can change.

> In your example **English: MMM D, YYYY h:mm a** what does "a" stand for?

See documentation here: https://momentjs.com/docs/#/displaying/format/
> a  | am pm

**Comment by MarineDBL** [comment]
Ok clear. 
I'd remove the comma but if it's too much work, don't bother.

**Review by MarineDBL — APPROVED** [review]

**Review by CedricPerotto — CHANGES_REQUESTED** [review]
LGTM, we would like to integrate it in a blip version to validate locale tests. 

Please add a 0.12.2 release.

**Review by CedricPerotto — APPROVED** [review]

**Pull request merged**
